### ISSUE TITLE
I can't run the test suite either with 'learn' or 'npm test' command

### ISSUE THREAD

**Issue by ldgarber** [learn-co-curriculum/js-ajax-callbacks-lab#23]
When I run the test suite after forking and cloning the lab, I get this error message: 

js-ajax-callbacks-lab@1.0.0 test /Users/leahgarber/Development/code/js-ajax-callbacks-lab-v-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

/Users/leahgarber/Development/code/js-ajax-callbacks-lab-v-000/test/index-test.js:15
  let $
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/leahgarber/Development/code/js-ajax-callbacks-lab-v-000/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/leahgarber/Development/code/js-ajax-callbacks-lab-v-000/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/leahgarber/Development/code/js-ajax-callbacks-lab-v-000/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/leahgarber/Development/code/js-ajax-callbacks-lab-v-000/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

I expect to be able to run the tests

**Comment by Traci7822** [comment]
Issue is still present, student was able to get tests to pass by removing "mocha -R mocha-multi --reporter-options nyan=-,json=.results.json" from package.json.
