### ISSUE TITLE
Tests pass in browser but not in terminal

### ISSUE THREAD

**Issue by dannyd4315** [learn-co-curriculum/js-ajax-callbacks-lab#7]
Jasmine tests are passing in the browser for this lab but not in the console - error below

```
MadLib should replace verbs


    at file:///Users/dannydawson/Development/code/js-ajax-callbacks-lab-v-000/spec/mad_lib_spec.js:16:26
    at attemptSync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1510:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1498:20)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:306:28)
    at file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1708:44
    at attemptAsync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1520:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1496:28)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1694:21)
    at file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1708:44
    at attemptAsync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1520:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1496:28)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1694:21)
    at file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:541:83
    at attemptAsync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1520:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1496:28)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:548:25)
    at onload (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/boot.js:172:16)




MadLib should replace nouns


    at file:///Users/dannydawson/Development/code/js-ajax-callbacks-lab-v-000/spec/mad_lib_spec.js:30:26
    at attemptSync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1510:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1498:20)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:306:28)
    at file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1708:44
    at attemptAsync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1520:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1496:28)
    at next (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1517:40)
    at complete (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:333:19)
    at clearStack (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:506:11)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1505:22)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:306:28)
    at file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1708:44
    at attemptAsync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1520:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1496:28)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1694:21)
    at file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1708:44
    at attemptAsync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1520:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1496:28)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1694:21)
    at file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:541:83
    at attemptAsync (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1520:16)
    at run (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1496:28)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:1485:13)
    at queueRunnerFactory (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:518:42)
    at execute (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/jasmine.js:548:25)
    at onload (file:///Users/dannydawson/.rvm/gems/ruby-2.2.3/gems/learn-test-2.1.1/lib/learn_test/strategies/jasmine/boot.js:172:16)




2 specs, 2 failures
```

**Comment by pletcher** [comment]
Fixed with #10
